#!/usr/bin/env bash

psql datumbazo < test-resources/db/test-db/migrations/deploy/create-citext-extension.sql
psql datumbazo < test-resources/db/test-db/migrations/deploy/create-continents-table.sql
psql datumbazo < test-resources/db/test-db/migrations/deploy/create-countries-table.sql
psql datumbazo < test-resources/db/test-db/migrations/deploy/create-twitter-schema.sql
psql datumbazo < test-resources/db/test-db/migrations/deploy/create-twitter-users-table.sql
psql datumbazo < test-resources/db/test-db/migrations/deploy/create-twitter-tweets-table.sql
psql datumbazo < test-resources/db/test-db/migrations/deploy/create-twitter-tweets-users.sql

find test-resources
ls -l
lein run "postgresql://tiger:scotch@localhost/datumbazo" test-resources/db/test-db/fixtures load
