language: clojure

before_script:
  - "echo 'yes' | sudo apt-add-repository ppa:ubuntugis/ubuntugis-unstable"
  - "sudo apt-get update"
  - "sudo apt-get install libgeos-dev libgeos++-dev libproj-dev postgresql-9.1-postgis"
  - "psql -c \"CREATE DATABASE datumbazo;\" -U postgres"
  - "psql -c \"CREATE USER tiger SUPERUSER UNENCRYPTED PASSWORD 'scotch';\" -U postgres"
  - "psql -U postgres datumbazo < resources/db/test-db/migrations/deploy/create-postgis-extension.sql"
  - "psql -U postgres datumbazo < resources/db/test-db/migrations/deploy/create-citext-extension.sql"
  - "psql -U postgres datumbazo < resources/db/test-db/migrations/deploy/create-continents-table.sql"
  - "psql -U postgres datumbazo < resources/db/test-db/migrations/deploy/create-countries-table.sql"
  - "psql -U postgres datumbazo < resources/db/test-db/migrations/deploy/create-twitter-schema.sql"
  - "psql -U postgres datumbazo < resources/db/test-db/migrations/deploy/create-twitter-users-table.sql"
  - "psql -U postgres datumbazo < resources/db/test-db/migrations/deploy/create-twitter-tweets-table.sql"
  - "mysql -e \"CREATE DATABASE datumbazo;\""
  - "mysql -e \"CREATE USER 'tiger'@'%' IDENTIFIED BY 'scotch';\""
  - "mysql -e \"GRANT ALL ON *.* TO 'tiger'@'%' IDENTIFIED BY 'scotch';\""
  - "mysql -e \"FLUSH PRIVILEGES;\""

lein: lein2
