language: clojure

script: "lein test database.test.columns database.test.connection database.test.core database.test.examples database.test.serialization database.test.tables"

before_script:
  - "psql -c 'create database database_test;' -U postgres"
  - "psql -c \"create user database UNENCRYPTED PASSWORD 'database'\" database_test -U postgres"

postgres:
  adapter: postgresql
  database: database_test
  username: postgres