language: clojure

before_script:
  - "psql -c \"create database datumbazo;\" -U postgres"
  - "psql -c \"create user tiger UNENCRYPTED PASSWORD 'scotch';\" -U postgres"
  - "mysql -e \"create database datumbazo;\""
  - "mysql -e \"create user 'tiger'@'%' identified by 'scotch';\""

lein: lein2
