language: clojure

before_script:
  - "psql -c 'create database test;' -U postgres"
  - "psql -c \"create user tiger UNENCRYPTED PASSWORD 'scotch'\" test -U postgres"

lein: lein2

postgres:
  adapter: postgresql
  database: test
  username: postgres