language: clojure

before_script:
  - "psql -c 'create database database_test;' -U postgres"
  - "psql -c \"create user database2 UNENCRYPTED PASSWORD 'database'\" database_test -U postgres"

postgres:
  adapter: postgresql
  database: database_test
  username: postgres