language: clojure

before_script:
  - "psql -c 'create database datumbazo;' -U postgres"
  - "psql -c \"create user tiger UNENCRYPTED PASSWORD 'scotch'\" datumbazo -U postgres"
  - "psql -U postgres -f migrations/20120930100300-create-postgis-extension.up.sql"
  - "psql -U postgres -f migrations/20120930100400-create-postgis-topology-extension.up.sql"
  - "psql -U postgres -f migrations/20120930145553-create-continents-table.up.sql"
  - "psql -U postgres -f migrations/20120930153020-create-countries-table.up.sql"
  - "mysql -e 'create database datumbazo;'"

lein: lein2
