---
version: '2'

services:
  postgresql:
    image: "postgis/postgis:13-3.1"
    environment:
      POSTGRES_USER: "tiger"
      POSTGRES_DB: "datumbazo"
      POSTGRES_PASSWORD: "scotch"
    ports:
      - "5432:5432"

  mariadb:
    image: "mariadb:10.5.8"
    environment:
      MYSQL_DATABASE: "datumbazo"
      MYSQL_PASSWORD: "scotch"
      MYSQL_ROOT_PASSWORD: "scotch"
      MYSQL_USER: "tiger"
    ports:
      - "3306:3306"

  materialize:
    image: "materialize/materialized:v0.6.0"
    environment:
      MZ_WORKERS: "1"
    ports:
      - "6875:6875"
